### ISSUE TITLE
Ensure RC4 is deprecated

### ISSUE THREAD

**Issue by wsargent** [typesafehub/ssl-config#14]
Check that RC4 is deprecated -- I think this project was forked before the PR made it in.

https://github.com/playframework/playframework/issues/4240

**Comment by ktoso** [comment]
Thanks! Let's verify the codebase now to see if it's what we consider "most up to date, but still JDK6 compatible".
And then in January we drop JDK6.

**Comment by ktoso** [comment]
I checked and this change is included here already https://github.com/playframework/playframework/pull/4246/files :+1:
