### ISSUE TITLE
Prints to standard-out?

### ISSUE THREAD

**Issue by ennru** [typesafehub/ssl-config#41]
My code uses ssl-config 0.2.1 from via a Akka http 2.4.7 client and I get output of the sslConfig.config.loose.disableSNI config parameter to standard out or error whenever it connects to the server.

`2016-06-22 15:14:52,523 DEBUG spatcher-9            akka.io.TcpOutgoingConnection  Attempting connection to [host.com/1.7.1.2:443]`
`sslConfig.config.loose.disableSNI = false`

Nothing serious, but presumably easy to fix. I didn't find any suspicous println in the source.

**Comment by ktoso** [comment]
Thanks for reporting and sorry for the silly mistake.
It was in Akka itself, and is already fixed, see PR here: https://github.com/akka/akka/pull/20769/files

Thanks for reporting again :)
This will be soon released as part of 2.4.8
