### ISSUE TITLE
Unable to override hostname verifier

### ISSUE THREAD

**Issue by tummybunny** [typesafehub/ssl-config#46]
**SSLConfigSettings**

``` scala
def withHostnameVerifierClass(value: Class[javax.net.ssl.HostnameVerifier]): SSLConfigSettings = copy(hostnameVerifierClass = value)
```

should be

``` scala
def withHostnameVerifierClass(value: Class[_ <: javax.net.ssl.HostnameVerifier]): SSLConfigSettings = copy(hostnameVerifierClass = value)
```

Otherwise it won't let anyone to override with a custom hostname verifier.

**Comment by andrewrapp** [comment]
I'd like to be able to use this as well. I submitted a PR. Would be great to get this in. Thanks!

**Comment by ktoso** [comment]
Thanks for the PR, that's the way to get stuff done 👍 
Will bump the dependency soon in akka-http

**Comment by mehmetaydogdu** [comment]
When will 0.2.2 will be available? I need withHostnameVerifierClass functionality and do not want to clone master, create jar and put into my project.

**Comment by ktoso** [comment]
Maybe this or next week.

**Comment by ktoso** [comment]
Oh well, actually: *now*. (it's on its way to maven central)

Happy hakking 😉

**Comment by mehmetaydogdu** [comment]
Great speed 👍
