### ISSUE TITLE
Move documentation to Paradox

### ISSUE THREAD

**Issue by ktoso** [typesafehub/ssl-config#50]
Let's co-ordinate and move the docs of ssl-config to paradox as well ( https://github.com/lightbend/paradox ) .
I'm hoping to cross link to it from akka docs (and perhaps at that point in time play could do so as well).

cc @eed3si9n @wsargent

**Comment by jonas** [comment]
I can take this

**Comment by ktoso** [comment]
Would be awesome :) Thank you!
