### ISSUE TITLE
Decide namespace / repo for this project

### ISSUE THREAD

**Issue by ktoso** [typesafehub/ssl-config#7]
Since both Akka and Play depend on it right now, best would be to put it as typesafehub/ssl-config I think.

What about artifact name? `"com.typesafe" % "ssl-config"`? 
Similar to Typesafe Config.

**Comment by ktoso** [comment]
// cc @wsargent @rkuhn sounds good?

I'm actually not sure if I'm allowed to release under com.typesafe hm...

**Comment by rkuhn** [comment]
Yes, proposals sound good. Please get in touch with Eugene to clarify any possible obstacles.

**Comment by ktoso** [comment]
Okey, will do

**Comment by 2m** [comment]
It should also probably go to bintray under typesafe organization.

**Comment by ktoso** [comment]
Hey @eed3si9n,
we'll need to release this lib (to be shared by play and akka currently).
Does it indeed need to be in bintray as well? I'm somehow confused - why would it, we don't publish Akka (OSS) there for example.

This lib is to be open source.

**Comment by eed3si9n** [comment]
You can either do Bintray and then sync to Sonatype OSS, or publish straight to Sonatype OSS.
The difference is mostly administration of user list. Since you guys probably have access to Sonatype OSS, it shouldn't matter.

**Comment by ktoso** [comment]
Yup, thanks for confirming! So will push to Sonatype tomorrow.
