### ISSUE TITLE
Move documentation here

### ISSUE THREAD

**Issue by ktoso** [typesafehub/ssl-config#8]
Play has great docs on WS and HTTPS.
Akka will need them.

This project is the one hosting all the settings.

Where do we put the docs?

Putting them in 3 places sounds sub optimal but perhaps is the right thing, as here we can do in more detail and in Projects a bit less?

**Comment by wsargent** [comment]
I'm okay with putting them here under a subproject.

**Comment by ktoso** [comment]
I started that one somewhat backwards I guess :-)
What are the docs – I guess it's ripping out bits from the WS documentation (like the "if you intend to use this as TLS termination" etc)?

**Comment by wsargent** [comment]
https://github.com/playframework/playframework/tree/master/documentation/manual/detailedTopics/configuration/ws

**Comment by wsargent** [comment]
The TLS termination is about using SSL as a server -- the ssl config is mostly about using it as a client.

**Comment by ktoso** [comment]
Awesome thanks. Do you want to move it or shall I?

**Comment by ktoso** [comment]
> The TLS termination is about using SSL as a server -- the ssl config is mostly about using it as a client.

Yeah, agreed. That part should be in Akka HTTP – we'll recommend the same as you do with Play "terminate before the JVM plz, or if you must... then do this and that".

**Comment by wsargent** [comment]
I can move it.

**Comment by ktoso** [comment]
Great, thanks :+1:

**Comment by ktoso** [comment]
Thanks!
